### ISSUE TITLE
Data Augmentation？

### ISSUE THREAD

**Issue by WuDiDaBinGe** [amazon-research/sccl#1]
Should I need to process original dataset to get the data augmentation？I can't find the the code of data augmentation in this respo.

**Comment by sramakrishnan247** [comment]
@amazon-auto Any info on this?

**Comment by Dejiao2018** [comment]
Hello, our data augmentation is obtained via https://github.com/makcedward/nlpaug

Specifically, you may wanna check nlpaug.augmenter.word.ContextualWordEmbsAug

**Comment by WuDiDaBinGe** [comment]
OK Thanks

**Comment by MrRace** [comment]
@Dejiao2018  In the code:
```
train_text = train_data['text'].fillna('.').values
train_text1 = train_data['text1'].fillna('.').values
train_text2 = train_data['text2'].fillna('.').values
```
Could you public same of  datas or  subdata ?

**Comment by urospet** [comment]
> In `nlpaug.augmenter.word.ContextualWordEmbsAug` there are two parameters？
> 
> ```
> aug = naw.ContextualWordEmbsAug(model_path='bert-base-uncased', action="substitute")
> ```
> 
> What `model_path` do you choose ？ @Dejiao2018

"We augment the data via word substitution, and we choose Bertbase and Roberta to generate the augmented pairs"
