### ISSUE TITLE
Not sure how the augmented pairs generated by the Contextual Augmenter

### ISSUE THREAD

**Issue by qiuzx2** [amazon-research/sccl#14]
Hi, I am trying to reproduce the paper.  But I am not sure how the augmented pairs generated by the contextual augmenter. The paper shows that the data is augmented by Bertbase and Roberta via word substitution Does it mean that you augment the input sentence once by bertbase and roberta correspondingly and combine these two sentences the augmented pair, or it means that during the experiment, you just use one single pre-trained model (e.g., roberta) and use it to augment the sentence twice to get the augmented pair? I try the latter one way, i.e, use the roberta to generate the two augmented sentences for one sentence, but it did not work.

**Comment by Dejiao2018** [comment]
> Does it mean that you augment the input sentence once by bertbase and roberta correspondingly and combine these two sentences the augmented pair. 

Yes
