### ISSUE TITLE
Twitter dataset not found?

### ISSUE THREAD

**Issue by urospet** [amazon-research/sccl#2]
I am trying to reproduce the original paper, but I am not able to find the twitter dataset and the link (Yin and Wang, 2016) in the paper does not direct to the dataset.

**Comment by jelee0118** [comment]
I wonder about this, too.

**Comment by Dejiao2018** [comment]
You can find the data here https://github.com/rashadulrakib/short-text-clustering-enhancement/tree/master/data

**Comment by urospet** [comment]
Is there a way to get the data not already preprocessed (especially Google News)

**Comment by 1085737319** [comment]
> You can find the data here https://github.com/rashadulrakib/short-text-clustering-enhancement/tree/master/data

Is the first column in the data set a label or the second column is a label?

**Comment by Dejiao2018** [comment]
the first column is text_augment_1 and the second column is text_augment_2
