### ISSUE TITLE
No code found for dataset partitioning

### ISSUE THREAD

**Issue by gzpbbd** [amazon-research/sccl#21]
Did you divide the dataset into training dataset and test dataset? I didn't find any content related to dataset partitioning in the paper. In the code corresponding to the paper, I found that there are data files named 'test' and 'train', but it seems that the main program file 'main.py' uses the same file specified by argument 'dataname' when training and testing.

**Comment by Dejiao2018** [comment]
As this is purely unsupervised learning, so there is no training set and testing set split.
