### ISSUE TITLE
Doubt regarding dataloader file

### ISSUE THREAD

**Issue by Sohanpatnaik106** [amazon-research/sccl#5]
I have a small doubt in the file dataloader.py under the dataloader directory. In the function augment_loader, the train_label makes sense i.e., if train_text1 and train_text2 belong to same parent, then it is 1, otherwise it is -1. But, in the function train_unshuffle_loader, I don't get the use of train_label. Can you please explain that?

**Comment by Dejiao2018** [comment]
train_label is used to evaluate the clustering acc or NMI if the ground truth cluster labels are available. It's only used for evaluation.
